name: context-propagation
services:
    backend:
        container_name: backend
        build: backend
        environment:
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
            OTEL_SERVICE_NAME: "backend"
    frontend:
        container_name: frontend
        build: frontend
        environment:
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
            OTEL_SERVICE_NAME: "frontend"
    sprint-client:
        container_name: spring-client
        build: client
        environment:
            SERVER_ENDPOINT: "http://frontend:8080"
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
            OTEL_SERVICE_NAME: "client"
    jaeger:
        image: jaegertracing/all-in-one:1.44
        container_name: jaeger
        environment:
            COLLECTOR_OTLP_ENABLED: true
        ports:
          - "4318:4318"
          - "4317:4317"
          - "5775:5775"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "8090:16686"
          - "14268:14268"
          - "14250:14250"
          - "9411:9411"



