version: '3.8'

services:
  myapp:
      build: .
      container_name: app
      depends_on:
          - jaeger
      environment:
         OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4318/v1/traces"
  jaeger:
        image: jaegertracing/all-in-one:1.44
        container_name: jaeger
        environment:
            COLLECTOR_OTLP_ENABLED: true
        ports:
          - "4318:4318"
          - "4317:4317"
          - "5775:5775"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "8090:16686"
          - "14268:14268"
          - "14250:14250"
          - "9411:9411"

